# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Contraints.xdc

# IP: ip/MBMC/MBMC.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MBMC || ORIG_REF_NAME==MBMC} -quiet] -quiet

# Block Designs: bd/Protogen/Protogen.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Protogen || ORIG_REF_NAME==Protogen} -quiet] -quiet

# IP: bd/Protogen/ip/Protogen_xlconstant_0_0/Protogen_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Protogen_xlconstant_0_0 || ORIG_REF_NAME==Protogen_xlconstant_0_0} -quiet] -quiet

# IP: bd/Protogen/ip/Protogen_processing_system7_0_2/Protogen_processing_system7_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Protogen_processing_system7_0_2 || ORIG_REF_NAME==Protogen_processing_system7_0_2} -quiet] -quiet

# IP: bd/Protogen/ip/Protogen_xlconcat_0_0/Protogen_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Protogen_xlconcat_0_0 || ORIG_REF_NAME==Protogen_xlconcat_0_0} -quiet] -quiet

# IP: bd/Protogen/ip/Protogen_rst_Zynq_100M_0/Protogen_rst_Zynq_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Protogen_rst_Zynq_100M_0 || ORIG_REF_NAME==Protogen_rst_Zynq_100M_0} -quiet] -quiet

# IP: bd/Protogen/ip/Protogen_rst_Zynq_62M_0/Protogen_rst_Zynq_62M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Protogen_rst_Zynq_62M_0 || ORIG_REF_NAME==Protogen_rst_Zynq_62M_0} -quiet] -quiet

# IP: bd/Protogen/ip/Protogen_smartconnect_0_0/Protogen_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Protogen_smartconnect_0_0 || ORIG_REF_NAME==Protogen_smartconnect_0_0} -quiet] -quiet

# IP: bd/Protogen/ip/Protogen_Matrix_Driver_0_2/Protogen_Matrix_Driver_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Protogen_Matrix_Driver_0_2 || ORIG_REF_NAME==Protogen_Matrix_Driver_0_2} -quiet] -quiet

# IP: ip/MBMC/MBMC.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MBMC || ORIG_REF_NAME==MBMC} -quiet] -quiet

# XDC: c:/Protogen/Protogen.gen/sources_1/bd/Protogen/Protogen_ooc.xdc
